const sampleData = [
  {
    id: 1,
    wid: 104,
    watch_name: 'Myst',
    series: 'Revolver',
    size: 42,
    watch_price: 140,
    watch_id: 5,
    strap_id: 1,
    strap_name: 'Black Leather',
    strap_image: 'https://s3.amazonaws.com/watch-straps/BlackLeather_BlackMatte_260x.progressive.jpg',
    strap_price: 35,
  },
  {
    id: 4,
    wid: 104,
    watch_name: 'Myst',
    series: 'Revolver',
    size: 42,
    watch_price: 140,
    watch_id: 5,
    strap_id: 4,
    strap_name: 'Charcoal Nylon',
    strap_image: 'https://s3.amazonaws.com/watch-straps/Charcoal_Black_260x.progressive.jpg',
    strap_price: 30,
  },
  {
    id: 5,
    wid: 104,
    watch_name: 'Myst',
    series: 'Revolver',
    size: 42,
    watch_price: 140,
    watch_id: 5, 
    strap_id: 5,
    strap_name: 'Tan Leather',
    strap_image: 'https://s3.amazonaws.com/watch-straps/TanLeather_BlackBrushed_260x.progressive.jpg',
    strap_price: 35,
  },
];
