version: '3'

services:
  database:
    build: database/
    ports: '3306:3306'
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: student

  server:
    build: server/
    depends_on:
      - 'database'
    ports: 
      - '3002:3002'